### ISSUE TITLE
Incorrect object rest syntax parses differently than tsc

### ISSUE THREAD

**Issue by sandersn** [microsoft/typescript-go#140]
`const { ...rest: notAllowed } = x` puts the DotDotDotToken after `rest`, not `before`.

See  _submodules/TypeScript/tests/cases/conformance/salsa/plainJSGrammarErrors.ts

I'm not sure if this is an error in the visitor or the parser.

**Comment by DanielRosenwasser** [comment]
Fixed by #157.
